### ISSUE TITLE
build fails because of old version of package dmpc

### ISSUE THREAD

**Issue by ohylli** [soulski/dmp-scenario#1]
When trying to build this project with make build, the build fails because of multiple erros 
about undefined stuff from package dmpc for example dmpc.CreateErrorResult and dmpc.CreateMsgResult. The [output](https://github.com/soulski/dmp-scenario/files/782720/error.txt) from make is in the attached file.
 When looking at the repository [soulski/dmp-cli]( https://github.com/soulski/dmp-cli)
I noticed  that its latest commit is from March of last year where as the latest commit of this repository is from June. It seems that this repository uses a version of the dmpc package that has not been commited to GitHub. Would it be possible to get that version to GitHubb so that this project could be build?

**Comment by soulski** [comment]
@ohylli I did updated dmp-cli already. Could you re-build it again? Is there any problem please tell me.

**Comment by ohylli** [comment]
Build succeeds now and the system seems to work correctly. Thank you for fixing this.
